services:
  auto-md:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi.py